# Local MySQL DB, start with $ docker-compose up
# For more details to configuration see: https://medium.com/@etiennerouzeaud/play-databases-with-adminer-and-docker-53dc7789f35f
version: "3.1"
services:
  db:
    image: mysql:5.7
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: develop

  adminer_container:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    environment: 
      ADMINER_DESIGN: pepa-linha