name: DEPLOY

on:
  repository_dispatch:
    branches: 
      - master

defaults:
  run:
    working-directory: frontend  

env:
  GRIDSOME_API_URL: ${{ github.event.action }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.REMOTE_SSH_KEY}}  
        host: ${{  secrets.REMOTE_HOST  }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        passphrase: ${{ secrets.REMOTE_PASSPHRASE }} 
        password: ${{ secrets.REMOTE_PASSWORD }}
        source: "frontend/dist/"
        target: ${{ secrets.REMOTE_TARGET }}
        # copy only files from source dir to target dir ("strip" removes "frontend/dist" from the path)  
        strip_components: 2
       
